### ISSUE TITLE
Sorting search results by year

### ISSUE THREAD

**Issue by goldturtle** [WormBase/textpresso#37] opened 2015-06-30 19:42 UTC
Introducing sorting search results by publication year. Later on more bib fields may follow.

**Comment by vanaukenk** [comment] 2016-07-05 14:45
There is a check box for this feature under the Additional Search Options, but it doesn't appear to be working.
What is the current status of this feature?

**Comment by liyuling** [comment] 2016-07-05 20:46
I did some testings on the "sort by year" feature, just haven't checked in the codes yet. now it's dummy. I will update this ticket once it's in.

**Comment by liyuling** [comment] 2016-07-11 22:38
The code has been checked-in, next build on sandbox will have "sortbyyear" enabled.  a little bit more processing time should be anticipated when using this checkbox.

**Comment by vanaukenk** [comment] 2016-07-21 18:20
Hi,
I've been testing this feature today and it doesn't seem to be working quite right when I perform multiple searches.
If I perform a simple keyword search and then sort by year, it seems to work okay.
But if I then perform a second search and try to sort by year, the number of matches and documents matches the second search, but the papers that get returned are from the first search, no sentences get displayed, and each paper has the same doc score of -2.91.
A third search exhibits the same behavior, but the doc score for that search is -2.56.
I can do a demo or provide exact search parameters, if needed to help troubleshoot.

**Comment by liyuling** [comment] 2016-07-21 20:26
Thanks for testing. I will take a look at it today, i guess i can find the problem. maybe resetting the new variables that I introduced for this sort-by-year function, for each new search.

**Comment by liyuling** [comment] 2016-07-21 22:09
As expected, the bug was caused by not resetting some global variables before each new search. now it has been fixed in code base, should apply on next build on sandbox.

**Comment by liyuling** [comment] 2016-07-21 22:22
the fix has been applied on sandbox now. and it should solve the issue.

**Closed as completed** 2017-04-17 17:40 UTC
Labels: enhancement
